services:
  web:
    build: .
    container_name: contemporary-web
    environment:
      NEXT_PUBLIC_API_BASE: https://backoffice.thecontemporary.news
    restart: unless-stopped
    ports:
      - '3000:3000'
